[WIP] Issue #322: modified install.rst for clarity
DeepRegNet/DeepReg pull request #327
Opened 2020-08-25 00:18 UTC by shannonxtreme

# Description

 - Added spacing before conda links
 - Updated the link formatting for the WSL URL to be compliant with rst
 - Removed unnecessary words from Install the package

## Type of change

Please delete options that are not relevant.

- [ ] This change is a documentation update

2020-08-25 09:08 UTC, mathpluscode commented on docs/source/getting_started/quick_start.md
> +More details and other options can be found in [Command line tools](cli.md).
thx for fixing the wrong link, the `cli.md` might need to be replaced by `../docs/cli.md`

I didn't have the chance to add the docs for using readthedocs yet, but i belive you can test locally with `make clean html` under `docs/`

2020-08-25 21:34 UTC, mathpluscode requested changes
please correct the link to cli.md ;) thx

2020-08-25 23:04 UTC, shannonxtreme commented
> 
> 
> please correct the link to cli.md ;) thx

Will do! Side note, not sure how to test locally. Is there a guide somewhere? Thanks!

2020-08-25 23:51 UTC, mathpluscode commented
> > please correct the link to cli.md ;) thx
> 
> Will do! Side note, not sure how to test locally. Is there a guide somewhere? Thanks!

Hi, I just added a page regarding the docs here https://deepreg.readthedocs.io/en/325-improve-contributing-pages/contributing/docs.html It will be merged to master later.

Also, there's a new page about setting up your loader dev env here https://deepreg.readthedocs.io/en/325-improve-contributing-pages/contributing/setup.html.

Please feel free to give us feedback on these pages and other docs. Thanks!

2020-08-25 23:52 UTC, mathpluscode approved these changes

2020-08-25 23:52 UTC, merged

2020-08-26 00:46 UTC, shannonxtreme commented
> Side note: your last commit message was "Update cli.md link with correct dir structure", please include the issue number next time as suggested here https://deepreg.readthedocs.io/en/latest/contributing/commit.html ;) thx for understanding!

I'm so sorry! It's automatic sometimes for me. I'll pay more attention! Thanks for the links :)