[WIP] paired lung ct review
DeepRegNet/DeepReg pull request #333
Opened 2020-08-26 08:48 UTC by NMontanaBrown

# Description

Review:

- [ ] Author
- [ ] Disclaimer
- [ ] Application
- [ ] Data
- [ ] Instructions
- [ ] Pre-trained Model
- [ ] Tested version
- [ ] Contact
- [ ] References

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-08-26 09:23 UTC, NMontanaBrown commented
Problem with visualisation, overlapping titles:
![visualisation](https://user-images.githubusercontent.com/56116848/91285897-0c8a8b80-e78e-11ea-9913-a0f99936911e.png)

Modifying such that titles don't overlap

2020-08-26 09:31 UTC, NMontanaBrown commented
Fixed to:

![visualisation](https://user-images.githubusercontent.com/56116848/91287120-99821480-e78f-11ea-9c0e-c6d9839e7cc4.png)

2020-08-26 14:55 UTC, s-sd commented
@NMontanaBrown, just saw this. I might have a suggestion to test train. I think we can run it for a small number of epochs like 4 with save_freq of 2 to see that a model is being saved. Then we can load in that saved model with predict to see that it can be loaded in correctly. I think that would show that train is working as intended for that demo.

2020-08-27 21:54 UTC, mathpluscode commented on demos/paired_ct_lung/README.md
>  ## Data
Can you move the data section and add contact as in https://raw.githubusercontent.com/DeepRegNet/DeepReg/master/docs/source/demo/readme_template.md

thx!

2020-08-27 21:54 UTC, mathpluscode requested changes
please move data section and add contact section, then remove WIP once ready ;) thx

2020-08-29 18:20 UTC, mathpluscode commented
@NMontanaBrown  is this branch ready for merge? We'd better merge them now before switch default branch to main as PRs will have to be retargeted https://github.com/github/renaming

2020-08-29 18:51 UTC, mathpluscode approved these changes

2020-08-29 21:39 UTC, YipengHu approved these changes

2020-08-29 22:14 UTC, merged