Multiple loss functions
DeepRegNet/DeepReg pull request #662
Opened 2021-02-01 14:00 UTC by acasamitjana

# Description

Support the specification of >1 loss functions for each loss type "image", "label", "regularization". I'm not sure it make sense to use multiple loss functions for regularization but anyway it's done.

A config file example is:
```
loss:
  "image"
      - "name": "ssd"
         "weight": 0.5
      - "name": "lncc"
         "weight": 0.5
  "label"
       "name": "cross-entropy"
       "weight": 1.0
  "regularization":
        "name": "bending"
        "weight": 0.1
...
```
      
Fixes #526 

## Type of change

What types of changes does your code introduce to DeepReg?

_Please check the boxes that apply after submitting the pull request._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation Update (fix or improvement on the documentation)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (if none of the other choices apply)

## Checklist

_Please check the boxes that apply after submitting the pull request._

_If you're unsure about any of them, don't hesitate to ask. We're here to help! This is
simply a reminder of what we are going to look for before merging your code._

- [X] I have
      [installed pre-commit](https://deepreg.readthedocs.io/en/latest/contributing/setup.html)
      using `pre-commit install` and formatted all changed files. If you are not
      certain, run `pre-commit run --all-files`.
- [X] My commits' message styles matches
      [our requested structure](https://deepreg.readthedocs.io/en/latest/contributing/commit.html),
      e.g. `Issue #<issue number>: detailed message`.
- [X] I have updated the
      [change log file](https://github.com/DeepRegNet/DeepReg/blob/main/CHANGELOG.md)
      regarding my changes.
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

2021-02-02 11:37 UTC, acasamitjana commented
Hi, @mathpluscode @YipengHu can you take a look at that? It's related to one of your previous comments.

2021-02-02 11:42 UTC, acasamitjana commented
Hi, @mathpluscode @NMontanaBrown can you take a look at that? Really, it's not much. Now, the loss under each type (e.g, "image") can be a list(DictWrapper()) or a DictWrapper() for >1 or 1 losses, respectively.
To do that, I'm converting the later to a list in the code. If you know a better way to do it, I'm all ears!

2021-02-02 15:42 UTC, NMontanaBrown approved these changes
Nice work, thanks @acasamitjana :)

2021-02-02 20:21 UTC, YipengHu approved these changes
@acasamitjana multiple losses on ddf will be very useful for practical applications, such as known correspondence - one user can add readily with register

2021-02-02 21:31 UTC, mathpluscode requested changes
Related documents need to be updated.

2021-02-02 21:32 UTC, mathpluscode commented on deepreg/model/network.py
> +        loss_list = self.config["loss"][name]
I may prefer the var `loss_configs` or `loss_config_list`

2021-02-02 21:34 UTC, mathpluscode commented on test/unit/test_config_v011.py
> +    def test_parse_old_loss(self):
the test name should be `test_parse_single_loss`

2021-02-02 21:38 UTC, mathpluscode commented
@acasamitjana I think the most important is to update the docs, otherwise nice work!

2021-02-03 10:11 UTC, acasamitjana commented
@mathpluscode what do you think about the docs update? I've added some text + example in "Multiple Loss" (now reads "Composite Loss", which I think is more accurate). Feel free to request any changes.

2021-02-03 10:35 UTC, mathpluscode approved these changes

2021-02-03 13:02 UTC, merged